name: Branch Checks
description: Action to run branch checks for code consistency

runs:
  using: composite
  steps:
    - name: Format Checks
      shell: bash
      run: |
        pnpm format:check
    - name: Lint Checks
      shell: bash
      run: |
        pnpm lint
    # Add additional branch checks here
