name: Continuous Integration

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: dev
    env:
      NX_APP_NAME: ${{ vars.NX_APP_NAME }}
      API_URL: ${{ vars.API_URL }}
      NX_CONFIG_ONE: ${{ secrets.NX_CONFIG_ONE }}
      NX_CONFIG_TWO: ${{ secrets.NX_CONFIG_TWO }}
      NX_CONFIG_THREE: ${{ secrets.NX_CONFIG_THREE }}
      INTERNAL_CONFIG: ${{ secrets.INTERNAL_CONFIG }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup NODE_MODULES cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Format Checks
        run: |
          pnpm format:check

      - name: Lint Checks
        run: |
          pnpm lint

      - name: Build app
        run: pnpm build --skip-nx-cache
