name: Continuous Integration

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: dev
    env:
      NX_APP_NAME: ${{ vars.NX_APP_NAME }}
      API_URL: ${{ vars.API_URL }}
      NX_CONFIG_ONE: ${{ secrets.NX_CONFIG_ONE }}
      NX_CONFIG_TWO: ${{ secrets.NX_CONFIG_TWO }}
      NX_CONFIG_THREE: ${{ secrets.NX_CONFIG_THREE }}
      INTERNAL_CONFIG: ${{ secrets.INTERNAL_CONFIG }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM and Node
        uses: ./.github/actions/setup-pnpm-node
      - name: Branch checks
        uses: ./.github/actions/branch-checks
      - name: Build app
        uses: ./.github/actions/build-app
